### PR TITLE
feat: import original notebook

### PR DESCRIPTION
**Pull request by severo**
For https://observablehq.com/@fil/spherical-contours, for example, it avoids
having to prepare a special notebook like
https://observablehq.com/@fil/standalone-app-notebook

### CODE REVIEW

**Comment by severo** [comment]
(even if the code is horrible :-/) Maybe we could improve this, but it would require creating new files (a JSON with the data paths to replace, or somehting else)

**Comment by Fil** [comment]
~~Alternatively, we could have a special instruction that we would autodetect, like:
`d3.json(localUrl("………"))`~~

**Comment by Fil** [comment]
I agree with the goal, but I'm not convinced by the logic of this approach… for example if you want to update your notebook's code you shouldn't have to download the data again.

#3 has a different approach that just intercepts all fetch() calls and reroutes them to the local file.

**Comment by severo** [comment]
#3 is a much better implementation

**Pull request closed without merging**
